name: Contributor Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Contributors with contributions count
      - name: Contributors with contributions count
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.contributors.contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: rajat12826
          plugin_contributors: yes
          plugin_contributors_contributions: yes

      # Step 2: Contributors by categories
      - name: Contributors by categories
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.contributors.categories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: rajat12826
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "üß© Plugins / üñºÔ∏è templates": ["source/plugins/**", "source/templates/**"],
              "üìö Documentation": ["README.md", "**/README.md", "**/metadata.yml"],
              "üíª Code (other)": ["source/**", "Dockerfile"]
            }
