# Read the full reference here: https://github.com/lowlighter/metrics/blob/master/action.yml
permissions:
  contents: write

name: Most Used Languages

on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  
  # Allow manual run
  workflow_dispatch:
  
  # Run on push
  push:
    branches: ["master", "main", "metrics"]

jobs:
  most-used-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake,
            shell, gnuplot
          plugin_languages_limit: 4
