permissions:
  contents: write

name: Recent Activity Charts

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - metrics

jobs:
  recent-activity-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Generate activity chart
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rajat12826
          filename: assets/metrics.plugin.habits.charts.svg
          base: ""

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: no

          # Most stable window
          plugin_habits_days: 30
          plugin_habits_from: all
          plugin_habits_trim: yes

          config_timezone: Asia/Kolkata
          config_order: habits
