# Read the full reference here: https://github.com/lowlighter/metrics/blob/master/action.yml
permissions:
  contents: write

name: Recent Activity Charts

on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:
  push:
    branches: ["master", "main", "metrics"]

jobs:
  recent-activity-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          # Habits plugin
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          
          # ðŸ”§ Stability Fixes
          plugin_habits_days: 7
          plugin_habits_events_limit: 100
          plugin_habits_trim: yes
          
          config_timezone: Asia/Kolkata
